all:
  vars:
    etcd_data_dir: /var/lib/etcd
    cfssl_image: kerneltzo/command_runner:cfssl-latest
    etcd_image: quay.io/coreos/etcd:v3.5.0
  children:
    etcd_nodes:
      hosts:
        node1:
          ansible_host: 158.101.222.29
          ansible_user: ubuntu
          etcd_name: node-maxime
          etcd_ip: 158.101.222.29
          etcd_domain_name: etcd-node-maxime.apoorva64.com
        node2:
          ansible_host: 158.178.207.158
          ansible_user: ubuntu
          etcd_name: node-apoorva
          etcd_ip: 158.178.207.158
          etcd_domain_name: etcd-node-apoorva.apoorva64.com
        node3:
          ansible_host: 129.151.254.9
          ansible_user: ubuntu
          etcd_name: node-raphael
          etcd_ip: 129.151.254.9
          etcd_domain_name: etcd-node-raphael.apoorva64.com
